### ISSUE TITLE
Interfaces is not exported in index

### ISSUE THREAD

**Issue by Trickfilm400** [Kopf02/express-utils#1]
The interface (https://github.com/Kopf02/express-utils/blob/main/src/interfaces/HttpResponseInterface.ts#L3)
```ts
export interface Error {
  error: string;
  errorDetails?: ValidationErrorItem[];
}
```

which is used in HTTP exceptions: https://github.com/Kopf02/express-utils/blob/main/src/exceptions/HttpException.ts#L15

### Issue
You cannot use this interface in custom exceptions if you want to overwrite the function in the reference above, because it is not exported in https://github.com/Kopf02/express-utils/blob/main/src/index.ts#L8

### Todo
Add the nterface to the export statement in the `src/index.ts` file

**Comment by Kopf02** [comment]
has been fixed in https://github.com/Kopf02/express-utils/commit/58f5a1e830d23736e2f7b12991b82f1717d43c61
