### ISSUE TITLE
errorMiddleware: check for HttpExcention instance

### ISSUE THREAD

**Issue by Trickfilm400** [Kopf02/express-utils#3]
## Issue
if you pass anything but an  `HttpException` to the errorMiddleware via `next`, an `TypeError: error.getBody is not a function` error will be thrown.

## Todo
Check if the given value is an instance of `HttpException`, and if not wrap it in an `Unknown Server Error` Exception with the given value as a custom error message as details

**Comment by Kopf02** [comment]
Fixed in 17492ee8a28d79566c3d52d77edf2836c3a6eb51
