### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by Trickfilm400** [Kopf02/express-utils#7]
What about the idea to listen to 443 (or any other port like 8443) with SSL/TLS Support if there is a SSL certificate on the filesystem (or with a config option)?

This would help with local development which needs SSL (like OIDC for example or other use-cases);
as well it can impove security in the deployments, if the connections are secured from end-to-end, even between the service and reverse proxy (also would enable correct http2 support)

I've added a SSL server myself (are not calling the included .listen function)
```typescript
const httpsOptions = {
  key: fs.readFileSync('./cert.key'),
  cert: fs.readFileSync('./cert.pem'),
};
const SSLserver = https
   .createServer(httpsOptions, app.getServer())
   .listen(8080, () => {
      console.log('ssl server running at ' + 8080);
});
```

**Comment by Kopf02** [comment]
Implemented in 3b73a3978fcb872d1e9415fcb690635ca6ab413a
